# Site settings
title:          "Mario's Blog"
description:    "Minimal Jekyll theme for storytellers"
url:            "http://blog.baldi.info"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:         
  name:         Mario Baldi
  url:          http://baldi.info
  email:        com@baldi.info

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

#remote_theme: chesterhow/tale

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
#  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:title
paginate:       50

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
